name: Build & Publish (Root)

on:
  push:
    branches:
      - root

    paths-ignore:
      - "yaml-files/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle (Build)
        run: ./gradlew build --no-daemon

      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v4

        with:
          name: Main JAR
          path: build/libs/*-all.jar

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v4

        with:
          name: JARs
          path: build/libs/*.jar

      - name: Upload artifacts (Module JARs)
        uses: actions/upload-artifact@v4

        with:
          name: Module JARs
          path: module-*/build/libs/*.jar

      - name: Gradle (Publish)
        env:
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.SIGNING_KEY_PASSPHRASE }}"
        run: |
          ./gradlew publish \
            "-Pmaven.url.snapshots=${{ secrets.SNAPSHOTS_URL }}" \
            "-Pmaven.url.releases=${{ secrets.MAVEN_URL }}" \
            "-Pmaven.user=${{ secrets.MAVEN_USERNAME }}" \
            "-Pmaven.password=${{ secrets.MAVEN_PASSWORD }}" \
            --no-daemon

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker build -t ghcr.io/quiltmc/cozy-discord:latest -t ghcr.io/quiltmc/cozy-discord:${GITHUB_SHA} .
      - run: docker push ghcr.io/quiltmc/cozy-discord:latest
      - run: docker push ghcr.io/quiltmc/cozy-discord:${GITHUB_SHA}

      - name: Dispatch quilt-helm-charts update event
        uses: peter-evans/repository-dispatch@v3
        with:
            token: ${{ secrets.QHC_TOKEN }}
            repository: QuiltMC/quilt-helm-charts
            event-type: cozy_update
            client-payload: '{"tag": "${{ github.sha }}"}'
